// eslint-disable-next-line no-undef
module.exports = {
  content: ["./src/**/*.tsx"],
  theme: {
    // fontFamily: {
    //   "ibm-regular": ["IBM Plex Sans", "sans-serif"],
    // },
    colors: {
      "carbon-layer": "#161616",
      "carbon-bg": "#E5E5E5",
      "carbon-bg-secondary": "#393939",
      "carbon-bg-secondary-hover": "#4C4C4C",
      "carbon-bg-secondary-active": "#6F6F6F",
      "carbon-label": "#525252",
      "carbon-field": "#FFFFFF",
      "carbon-field-placeholder": "#A8A8A8",
      "carbon-field-focus": "#0F62FE",
      "carbon-field-border": "#DFE3E6",
      "carbon-white": "#FFFFFF",
      "carbon-text-inverse": "#FFFFFF",
      "carbon-text-primary": "#161616",
      "carbon-text-secondary": "#525252",
      "carbon-bg-modal": "#F4F4F4",
      "carbon-bg-danger": "#DA1E28",
      "carbon-bg-danger-active": "#750E13",
      "carbon-bg-danger-hover": "#BA1B23",
      "carbon-brand": "#0F62FE",
      "carbon-brand-hover": "#0353E9",
      "carbon-brand-active": "#002D9C",
      "carbon-table-head": "#E0E0E0",
      "carbon-error-message": "#DA1E28",
      "notification-success": "#198038",
      "notification-warning": "#F1C21B",
      "notification-error": "#DA1E28",
      "notification-success-bg": "#24A14830",
      "notification-warning-bg": "#F1C21B30",
      "notification-error-bg": "#DA1E2830",
      "bg-main-00": "#f4f4f4",
      "bg-main-01": "#FFFFFF",
      "bg-main-02": "#F0F3F6",
      "bg-main-03": "#F5F7FA",
      "bg-danger": "#DA1E28",
      "bg-warning": "#F1C21B",
      "bg-success": "#198038",
      "text-01": "#152935",
      "text-02": "#5A6872",
      "brand-01": "#3d70b2",
      "border-00": "#DFE3E6",
      "border-01": "#e9edf0",
      "border-02": "#6FB5FB",
    },
  },
  plugins: [],
};
